name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-checks:
    runs-on: self-hosted
    permissions:
      id-token: write 
      contents: read

    steps:
      - name: Checkout repository code 
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        name: setup node
        with:
          node-version: 18      
      
      - uses: hashicorp/setup-terraform@v2
        name: Setup Terraform
        with: 
          terraform_version: 1.4.6

      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init

      - name: Terraform Validate
        working-directory: infrastructure
        run: terraform validate

      - name: Terraform format check
        working-directory: infrastructure
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: infrastructure
        run: terraform plan
